version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
     - /nfs-data/sites/${DIRECTORY_NAME}:/var/www/html
     # maak deze directory ook op de server aan!
    networks:
     - traefik-public
    logging:
      driver: json-file
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_DATABASE_HOST}
      WORDPRESS_DB_USER: ${MYSQL_DATABASE_USERNAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE_NAME}
    deploy:
      labels:
        traefik.http.services.CHANGETHIS.loadbalancer.server.port: '80'
        traefik.http.routers.CHANGETHIS-http.entrypoints: http
        traefik.http.routers.CHANGETHIS-https.rule: Host(`${DOMAIN}`)
        traefik.http.routers.CHANGETHIS-https.tls.certresolver: cloudflare
        traefik.http.routers.CHANGETHIS-https.entrypoints: https
        traefik.constraint-label: traefik-public
        traefik.http.routers.CHANGETHIS-http.middlewares: https-redirect
        traefik.http.routers.CHANGETHIS-https.middlewares: google-oauth@file
        traefik.http.routers.CHANGETHIS-https.tls: 'true'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.CHANGETHIS-http.rule: Host(`${DOMAIN}`)
      replicas: 1
      resources:
        limits:
          cpus: '0.6'
          memory: 600M
networks:
  traefik-public:
    external: true
