version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
     - /nfs-data/sites/${DIRECTORY_NAME}:/var/www/html
     # maak deze directory ook op de server aan!
    networks:
     - traefik-public
    logging:
      driver: json-file
    environment:
      WORDPRESS_DB_HOST: 10.111.0.5:25060
      WORDPRESS_DB_USER: ${MYSQL_DATABASE_USERNAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE_NAME}
    deploy:
      labels:
        traefik.http.services.${WEBSITE_NAME}.loadbalancer.server.port: '80'
        traefik.http.routers.${WEBSITE_NAME}-http.entrypoints: http
        traefik.http.routers.${WEBSITE_NAME}-https.rule: Host(`${DOMAIN}`)
        traefik.http.routers.${WEBSITE_NAME}-https.tls.certresolver: cloudflare
        traefik.http.routers.${WEBSITE_NAME}-https.entrypoints: https
        traefik.constraint-label: traefik-public
        traefik.http.routers.${WEBSITE_NAME}-http.middlewares: https-redirect
        traefik.http.routers.${WEBSITE_NAME}-https.middlewares: google-oauth@file
        traefik.http.routers.${WEBSITE_NAME}-https.tls: 'true'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.${WEBSITE_NAME}-http.rule: Host(`${DOMAIN}`)
      replicas: 1
networks:
  traefik-public:
    external: true
